#Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
#CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd/mm/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git fzf-zsh-plugin colored-man-pages ssh-agent macos zsh-syntax-highlighting asdf)

ZSH_THEME="powerlevel10k/powerlevel10k"


source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_GB.UTF-8
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="nvim"
export GOPATH="${HOME}/go"

# Add local gopath bin to path
export PATH=$GOPATH/bin:$PATH


alias edit_zshconfig="$EDITOR ~/.zshrc"
alias edit_ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias vim='nvim'

export FZF_DEFAULT_OPTS="--layout=reverse --info=inline --height=80% --multi --preview='([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2>/dev/null | head -n 200' --preview-window=':hidden' --color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008' --prompt='∼ ' --pointer='▶' --marker='✓' --bind '?:toggle-preview' --bind 'ctrl-a:select-all' --bind 'ctrl-e:execute(vim {+} >/dev/tty)' --bind 'ctrl-v:execute(code {+})' --bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'"

# Setup dir env
eval "$(direnv hook zsh)"

# Setup FZF keybindings
eval "$(fzf --zsh)"

zshrc_path="${HOME}/.dotfiles/zsh/"

HOST="$(hostname)"

# Common includes
source "${zshrc_path}/aliases/docker.zsh"
source "${zshrc_path}/aliases/git.zsh"
source "${zshrc_path}/aliases/macos.zsh"
source "${zshrc_path}/aliases/p10k.zsh"
source "${zshrc_path}/settings/ssh-agent.zsh"

# Personal Includes
if [[ "$hostname" == "saki.local" ]]; then
    
fi

# Work includes
if [[ "$hostname" == "shermanrose-mac-xh4fnh2g7y.corp.improbable.io" ]]; then
    source "${zshrc_path}/aliases/flutter.zsh"
    source "${zshrc_path}/aliases/gam.zsh"
    source "${zshrc_path}/aliases/gcloud.zsh"
    source "${zshrc_path}/aliases/nvm.zsh"
fi
